// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yuxplbgrdugbfgxsmtvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1eHBsYmdyZHVnYmZneHNtdHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MTIwMTMsImV4cCI6MjA1MDI4ODAxM30.Xg9lzQiyNlurB9DEEjdcfB5-FtAxYDb4F3yKhW7_dvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);